Update 5-0-stable.yml
Tries to fix error:

   cd /opt/redmine
  bundle exec rake redmine:plugins:test:units
  bundle exec rake redmine:plugins:test:functionals
  bundle exec rake redmine:plugins:test:integration
  shell: /usr/bin/bash -e {0}
  env:
    RAILS_ENV: test
    NAME: redmine_workload
rake aborted!
LoadError: cannot load such file -- /home/runner/work/test/test_helper
/home/runner/work/redmine_workload/redmine_workload/test/test_helper.rb:4:in `<top (required)>'
/opt/redmine/plugins/redmine_workload/test/unit/group_selection_test.rb:3:in `<top (required)>'
/opt/redmine/lib/tasks/redmine.rake:182:in `block (4 levels) in <top (required)>'
/opt/hostedtoolcache/Ruby/3.0.4/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/3.0.4/x64/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:test:units
(See full trace by running task with --trace)
Error: Process completed with exit code 1.